version: '3.9'

services:
  database:
    image: postgres
    container_name: database_basic_crud
    restart: always
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'
    expose:
      - ${TYPEORM_PORT}
    volumes:
      - pgdata:/data/postgres
    command: -p ${TYPEORM_PORT}
  redis:
    container_name: redis_basic_crud
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  app:
    build: .
    container_name: basic_crud
    command: yarn dev
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/app
    links:
      - database
      - redis
    depends_on:
      - database
    environment:
      - TYPEORM_HOST=database
      - REDIS_HOST=redis
volumes:
  pgdata:
    driver: local
